version: '3.8'

services:
  app:
    build:
      context: . 
      dockerfile: ./Dockerfile
    container_name: news_app  
    volumes:
      - .:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
    environment:
      - PHP_EXTENSION=pdo_mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel_user
      - DB_PASSWORD=laravel_user123
    depends_on:
      - mysql
    networks:
      - news_network  
    restart: always

  mysql:
    image: mysql:8.0
    container_name: news_db  
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_user123
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - news_network 
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - news_network  
    restart: always

  nginx:
    image: nginx:alpine
    container_name: news_nginx  
    volumes:
      - .:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8082:80
    depends_on:
      - app
    networks:
      - news_network  
    restart: always

volumes:
  dbdata:

networks:
  news_network:  
    driver: bridge
